name: Android CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Retrieve version
        run: |
          echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -PappVerName=${{ env.VERSION }} assembleRelease
      - name: Sign Android release
        if: success() && github.event_name != 'pull_request' && github.repository == '2926295173/hut'
        id: sign
        uses: r0adkll/sign-android-release@v1.0.4
        env:
          BUILD_TOOLS_VERSION: "32.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload built apk
        if: success() && github.event_name != 'pull_request' && github.repository == '2926295173/hut'
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: ${{ steps.sign.outputs.signedReleaseFile }}
      - name: Upload mappings
        if: success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: mappings
          path: "app/build/outputs/mapping/release"
      - name: Get apk info
        if: success() && github.event_name != 'pull_request' && github.repository == '2926295173/hut'
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: ${{ steps.sign.outputs.signedReleaseFile }}
